[package]
name = "krata-xenstore"
version = "0.0.24"
edition = "2021"
description = "A client that interacts with xenstore for krata"
license = "GPL-2.0-or-later"

[lib]
name = "xenstore"

[dependencies]
byteorder = "1"
libc = "0.2"
log = "0.4.22"
thiserror = "2.0.9"
tokio = { version = "1.41.1", features = ["full"] }
