[package]
name = "krata-xenclient"
version = "0.0.24"
edition = "2021"
description = "An implementation of Xen userspace for krata"
license = "GPL-2.0-or-later"

[lib]
name = "xenclient"

[dependencies]
async-trait = "0.1.85"
bit-vec = "0.8.0"
indexmap = "2.6.0"
krata-xencall = "^0.0.24"
krata-xenplatform = "^0.0.24"
krata-xenstore = "^0.0.24"
libc = "0.2"
log = "0.4.22"
regex = "1.11.1"
thiserror = "2.0.9"
tokio = { version = "1.41.1", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4"] }
